#!/usr/bin/env bash
# Regenerate MEMORY.md from the frontmatter of every memory file.
#
# MEMORY.md is a BUILD ARTIFACT — never hand-edit it. The single source of
# truth for each index line is the `title:` and `description:` frontmatter of
# the memory file itself. This script rebuilds the whole index from those,
# which makes index/file drift structurally impossible.
#
# Runs as a Stop hook; emits a systemMessage only when the index changed.
set -euo pipefail

MEM="/Users/james/.claude/projects/-Users-james-Documents-rnet-design-system/memory"
IDX="$MEM/MEMORY.md"
[ -d "$MEM" ] || exit 0

# Extract a top-level frontmatter scalar (handles optional surrounding quotes).
fm_value() {
  awk -v key="$2" '
    /^---[[:space:]]*$/ { fm++; next }
    fm==1 && $0 ~ "^" key ":[[:space:]]*" {
      sub("^" key ":[[:space:]]*", "")
      gsub(/^"/, ""); gsub(/"[[:space:]]*$/, "")
      print; exit
    }
  ' "$1"
}

tmp=$(mktemp)
{
  echo "# Memory index"
  echo
  echo "<!-- Generated by .claude/hooks/generate-memory-index.sh from each memory"
  echo "     file's title/description frontmatter. Do not hand-edit. -->"
  echo
  for f in "$MEM"/*.md; do
    [ -e "$f" ] || continue
    b=$(basename "$f")
    [ "$b" = "MEMORY.md" ] && continue
    title=$(fm_value "$f" title)
    [ -z "$title" ] && title=$(fm_value "$f" name)
    [ -z "$title" ] && title="${b%.md}"
    desc=$(fm_value "$f" description)
    if [ -n "$desc" ]; then
      echo "- [$title]($b) — $desc"
    else
      echo "- [$title]($b)"
    fi
  done
} > "$tmp"

if cmp -s "$tmp" "$IDX"; then
  rm -f "$tmp"
else
  mv "$tmp" "$IDX"
  echo '{"systemMessage":"MEMORY.md index regenerated from memory frontmatter."}'
fi
exit 0
