#!/usr/bin/env bash
# cdn/build.sh — Cloudflare Pages build step for cdn.rossie.net.
#
# Runs from the repo root (Pages root_dir = ""). Populates the rolling v1
# channel under /charts-and-vectors/css/v1/ and tokens/v1/ from the canonical
# root files, so the CDN never carries hand-copied duplicates that can drift.
#
# Pinned snapshots (css/pinned/N.N.N/, tokens/pinned/N.N.N/) are committed,
# frozen copies cut at release time — this script never writes them.
#
# Safe to run locally to preview the deploy tree; the channel output is
# .gitignored.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

CV=cdn/charts-and-vectors
CSS_SRC=(tokens.css colors_and_type.css controls.css markdown.css)

mkdir -p "$CV/css/v1" "$CV/tokens/v1"

# --- Rolling channel: the four layers, copied as-is -------------------------
# Their relative @import statements resolve within css/v1/ (all siblings).
for f in "${CSS_SRC[@]}"; do
  cp "$f" "$CV/css/v1/$f"
done

# --- Convenience bundle: one file, no @import waterfall ----------------------
# Concatenate the layers in dependency order, dropping the intra-bundle
# @import lines (every dependency is already inlined above its dependents).
{
  echo "/* rnet.css — JR / R—Net design system, full bundle (v1 channel)."
  echo "   Generated by cdn/build.sh: tokens + colors_and_type + controls +"
  echo "   markdown, concatenated. One <link>, no @import waterfall. */"
  for f in "${CSS_SRC[@]}"; do
    echo ""
    echo "/* ===== $f ===== */"
    grep -vE '^[[:space:]]*@import[[:space:]]+"(tokens|colors_and_type|controls|markdown)\.css"' "$f"
  done
} > "$CV/css/v1/rnet.css"

# --- Machine-readable tokens -------------------------------------------------
cp tokens.json "$CV/tokens/v1/tokens.json"

# --- Logos -------------------------------------------------------------------
# Published from the canonical source in components/rnet/ (outlined SVG + PNG),
# so the CDN carries no hand-copied duplicates that can drift. Filenames are
# stable and content is frozen per name, so these cache immutably (see
# _headers) — a logo revision adds a new filename, never mutates an existing
# one. If components/rnet/{svg,png} are missing, the source pack hasn't been
# built; run components/rnet/build-logos.sh first.
if [ -d components/rnet/svg ] && [ -d components/rnet/png ]; then
  mkdir -p "$CV/logos/svg" "$CV/logos/png"
  cp components/rnet/svg/*.svg "$CV/logos/svg/"
  cp components/rnet/png/*.png "$CV/logos/png/"
  logo_msg="$CV/logos/ ($(ls "$CV/logos/svg" | wc -l | tr -d ' ') svg + $(ls "$CV/logos/png" | wc -l | tr -d ' ') png)"
else
  logo_msg="logos SKIPPED (components/rnet/{svg,png} not built)"
fi

echo "built v1 channel: $CV/css/v1/ ($(ls "$CV/css/v1" | wc -l | tr -d ' ') files), $CV/tokens/v1/"
echo "published logos: $logo_msg"
